name: Deploy Futurecoder (Nginx container) to Azure Web App

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    env:
      IMAGE_NAME: futurecoder-nginx
      REGISTRY: ghcr.io/${{ github.repository_owner }}

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      # Deploy to an existing Linux Web App for Containers
      # Create the Web App once in the Azure Portal and add its Publish Profile
      # as a repo secret named AZUREAPPSERVICE_PUBLISHPROFILE
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "<YOUR_AZURE_WEBAPP_NAME>"   # <-- change this
          images: "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
