name: Deploy futurecoder to Azure Static Web Apps

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # --- Python build phase (futurecoder content generation) ---
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.1'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Make scripts executable
        run: chmod +x scripts/generate.sh || true

      - name: Generate site content
        env:
          FUTURECODER_LANGUAGE: en
        run: |
          poetry install --no-root
          ./scripts/generate.sh

      # --- Node build phase (frontend bundle -> outputs under frontend/course) ---
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Override CRA homepage to relative URLs
        working-directory: frontend
        run: |
          node -e "let p=require('./package.json'); p.homepage='.'; require('fs').writeFileSync('package.json', JSON.stringify(p,null,2)); console.log('homepage now', p.homepage)"

      - name: Install and build frontend
        working-directory: frontend
        env:
          CI: false
        run: |
          npm ci
          npm run build
          if [ -f "../course/service-worker.js" ]; then cp ../course/service-worker.js public/service-worker.js; fi

      - name: Verify build output
        run: |
          bash -eo pipefail <<'BASH'
          echo "frontend/course (summary):"
          find frontend/course -maxdepth 2 -type d -print
          # must exist:
          test -f frontend/course/index.html
          # pyodide dir should be there:
          test -d frontend/course/pyodide
          BASH


      # --- Stage deploy/ with /course and SWA routing rules ---
      - name: Stage files for SWA
        run: |
          bash -eo pipefail <<'BASH'
          set -e
          rm -rf deploy
          mkdir -p deploy/course
          cp -R frontend/course/* deploy/course/
      
          # root -> /course/
          cat > deploy/index.html <<'HTML'
          <!DOCTYPE html>
          <meta http-equiv="refresh" content="0; url=/course/">
          HTML
      
          # SWA routes: serve assets first, then SPA fallback
          cat > deploy/staticwebapp.config.json <<'JSON'
          {
            "routes": [
              { "route": "/", "redirect": "/course/", "statusCode": 302 },
      
              { "route": "/course/static/*",   "serve": "/course/static/*"   },
              { "route": "/course/pyodide/*",  "serve": "/course/pyodide/*"  },
              { "route": "/course/wheels/*",   "serve": "/course/wheels/*"   },
              { "route": "/course/packages/*", "serve": "/course/packages/*" },
              { "route": "/course/*.whl",      "serve": "/course/*.whl"      },
              { "route": "/course/*.wasm",     "serve": "/course/*.wasm"     },
              { "route": "/course/*.data",     "serve": "/course/*.data"     },
              { "route": "/course/*.js",       "serve": "/course/*.js"       },
              { "route": "/course/*.css",      "serve": "/course/*.css"      },
              { "route": "/course/*.map",      "serve": "/course/*.map"      },
              { "route": "/course/*.json",     "serve": "/course/*.json"     },
      
              { "route": "/course/*", "rewrite": "/course/index.html" }
            ],
            "mimeTypes": {
              ".wasm": "application/wasm",
              ".whl":  "application/octet-stream",
              ".data": "application/octet-stream"
            }
          }
          JSON
      
          echo "Show top-level folders in deploy:"
          find deploy -maxdepth 2 -type d -print
          BASH


      - name: Verify pyodide core exists in deploy
        run: |
          ls -la deploy/course/pyodide || true
          # core files should be present from the build
          test -f deploy/course/pyodide/pyodide.asm.js || echo "pyodide.asm.js not found (ok if using other backend)"
          # at least the directory must exist
          test -d deploy/course/pyodide

      # --- Deploy to Azure Static Web Apps (upload only; skip Oryx) ---
      - name: Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: upload
          app_location: "deploy"
          skip_app_build: true
