name: Deploy futurecoder to Azure Static Web Apps

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # --- Python phase (generate content for frontend) ---
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.1'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Make project scripts executable
        run: |
          chmod +x scripts/generate.sh || true
          chmod +x scripts/build.sh || true

      - name: Generate site content
        env:
          FUTURECODER_LANGUAGE: en
        run: |
          poetry install --no-root
          ./scripts/generate.sh

      # --- Node phase (install deps + build) ---
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci

      - name: Override CRA homepage to relative URLs
        working-directory: frontend
        run: |
          node -e "let p=require('./package.json'); p.homepage='.'; require('fs').writeFileSync('package.json', JSON.stringify(p,null,2)); console.log('homepage now', p.homepage)"

      - name: Build with project script
        env:
          FUTURECODER_LANGUAGE: en
          REACT_APP_USE_FIREBASE_EMULATORS: '1'
          REACT_APP_FIREBASE_STAGING: '1'
          CI: false
        run: ./scripts/build.sh

      # --- Where did the build land? (dist/course or frontend/course) ---
      - name: Detect course output dir
        id: outdir
        run: |
          if [ -d dist/course ]; then
            echo "dir=dist/course" >> $GITHUB_OUTPUT
          elif [ -d frontend/course ]; then
            echo "dir=frontend/course" >> $GITHUB_OUTPUT
          else
            echo "No course output found"; exit 1
          fi
          echo "Detected: $(cat $GITHUB_OUTPUT)"

      - name: Verify & normalize archives
        id: norm
        run: |
          OUT="${{ steps.outdir.outputs.dir }}"
          echo "OUT=$OUT"
          ls -la "$OUT" | sed -n '1,200p'
          test -f "$OUT/index.html"
          test -d "$OUT/pyodide"
          # normalize stdlib/core names if present
          STDLIB="$(find "$OUT" -type f -name 'python_stdlib*.zip' | head -n1 || true)"
          CORE="$(find "$OUT" -type f -name 'python_core*.tar' | head -n1 || true)"
          [ -n "$STDLIB" ] && cp -f "$STDLIB" "$OUT/python_stdlib.zip" || true
          [ -n "$CORE" ] && cp -f "$CORE" "$OUT/python_core.tar" || true
          test -f "$OUT/python_stdlib.zip"
          echo "dir=$OUT" >> "$GITHUB_OUTPUT"

      # --- Stage deploy folder ---
      - name: Stage files for SWA
        run: |
          bash -eo pipefail <<'BASH'
          set -e
          OUT="${{ steps.norm.outputs.dir || steps.outdir.outputs.dir || 'dist/course' }}"
          rm -rf deploy
          mkdir -p deploy/course
          cp -R "$OUT"/* deploy/course/

          # Root -> /course/
          cat > deploy/index.html <<'HTML'
          <!DOCTYPE html>
          <meta http-equiv="refresh" content="0; url=/course/">
          HTML

          # Keep routes *minimal* (SPA fallback + correct MIME)
          cat > deploy/staticwebapp.config.json <<'JSON'
          {
            "routes": [
              { "route": "/", "redirect": "/course/", "statusCode": 302 },
              { "route": "/course/*", "rewrite": "/course/index.html" }
            ],
            "mimeTypes": {
              ".wasm": "application/wasm",
              ".whl":  "application/octet-stream",
              ".data": "application/octet-stream",
              ".load_by_url": "application/octet-stream"
            }
          }
          JSON
          BASH

      # --- Vend Pyodide core tar as deploy/course/python_core.tar ---
      - name: Vendor Pyodide core tar (python_core.tar)
        run: |
          set -e
          OUT="${{ steps.norm.outputs.dir || steps.outdir.outputs.dir || 'dist/course' }}"
          mkdir -p deploy/course
          VER=$(node -p "require('./${OUT}/pyodide/package.json').version")
          echo "Pyodide version: $VER"
          URL1="https://cdn.jsdelivr.net/pyodide/v${VER}/full/pyodide-core-${VER}.tar.bz2"
          URL2="https://github.com/pyodide/pyodide/releases/download/${VER}/pyodide-core-${VER}.tar.bz2"
          echo "Fetching core tar..."
          if ! curl -LfsS --retry 3 --retry-delay 2 -H "User-Agent: GitHubActions" "$URL1" -o deploy/course/python_core.tar; then
            curl -LfsS --retry 3 --retry-delay 2 -H "User-Agent: GitHubActions" "$URL2" -o deploy/course/python_core.tar
          fi
          test -s deploy/course/python_core.tar

      # --- Create the exact hashed files your app requests (any path) ---
      - name: Materialize hashed python_core.load_by_url files
        run: |
          set -e
          CORE="deploy/course/python_core.tar"
          test -s "$CORE"
          # extract all unique filenames referenced in JS bundles
          mapfile -t NAMES < <(grep -rhoE "python_core\.tar\.[a-f0-9]{6,}\.load_by_url" deploy/course | sort -u || true)
          if [ "${#NAMES[@]}" -eq 0 ]; then
            echo "No hashed names found in bundles."
          else
            echo "Found ${#NAMES[@]} hashed filenames:"
            printf '%s\n' "${NAMES[@]}"
            # place the real tar at BOTH likely locations
            for name in "${NAMES[@]}"; do
              for base in "deploy/course" "deploy/course/static/js/static/media"; do
                mkdir -p "$base"
                cp -f "$CORE" "$base/$name"
              done
            done
          fi
          echo "Done."

      # --- Final checks ---
      - name: Verify deploy artifact essentials
        run: |
          test -s deploy/course/index.html
          test -d deploy/course/pyodide
          test -s deploy/course/python_stdlib.zip
          test -s deploy/course/python_core.tar
          echo "Listing any materialized hashed files:"
          find deploy/course -type f -name "python_core.tar*.load_by_url" -maxdepth 4 -exec ls -l {} \;

      - name: Print staticwebapp.config.json
        run: cat -n deploy/staticwebapp.config.json

      # --- Deploy to SWA (no Oryx build) ---
      - name: Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: upload
          app_location: "deploy"
          skip_app_build: true
